# Docker build and deploy image into docker hub

name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop, feature/** ]
jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [17]
        os: [ubuntu-latest]
        # imageName: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ github.event.repository.name }}:${{ github.sha }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.javaVersion }}
          cache: 'maven'
      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: wesco-chandanabuduru
          GITHUB_TOKEN: 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
        run: mvn -s settings.xml deploy
